apiVersion: apps/v1
kind: Deployment
metadata:
  name: tejasaiandem-kubernetes-deployment
  namespace: tj
  labels:
    app: tejasaiandem-kubernetes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tejasaiandem-kubernetes
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: tejasaiandem-kubernetes
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: environment
                    operator: In
                    values:
                      - production
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - tejasaiandem-kubernetes
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: new-docker-app
          image: newcontainerforaks.azurecr.io/tejasaiandem/kubernetes:latest
          ports:
            - containerPort: 5000
          livenessProbe:
            httpGet:
              path: /_status/healthz
              port: 5000
            initialDelaySeconds: 8
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /readiness
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 5
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: tejasaiandem-kubernetes-deployment
                  key: DB_HOST
      tolerations:  
        - key: "special"
          operator: "Exists"
          effect: "NoSchedule"