apiVersion: apps/v1
kind: Deployment
metadata:
  name: tejasaiandem-kubernetes-deployment
  namespace: tj
  labels:
    app: tejasaiandem-kubernetes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tejasaiandem-kubernetes
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: tejasaiandem-kubernetes
    spec:
      initContainers:
      - name: init-setup
        image: busybox:latest
        command: ['sh', '-c', 'ls; pwd; sleep 10']
        envFrom:
        - configMapRef:
            name: tejasaiandem-kubernetes-deployment
      containers:
      - name: tejasaiandem-kubernetes
        image: newcontainerforaks.azurecr.io/tejasaiandem/kubernetes:latest
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /_status/healthz
            port: 5000
          initialDelaySeconds: 8
          periodSeconds: 10
          failureThreshold: 3
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /readiness
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 5
        env:
        - name: tejasaiandem-kubernetes-deployment
          valueFrom:
            configMapKeyRef:
              key: DB_HOST
              name: tejasaiandem-kubernetes-deployment
